version: '2'
services:
  server:
    ports:
      - "7272:7272"
    build:
      context: .
      dockerfile: resources/docker/server/Dockerfile

  zalenium:
    image: dosel/zalenium:latest
    ports:
      - "4444:4444"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/videos:/home/seluser/videos
    privileged: true
    command: ["start",
             "--desiredContainers", "1",
             "--maxDockerSeleniumContainers", "1",
             "--screenWidth", "1920",
             "--screenHeight", "1080",
             "--videoRecordingEnabled", "true"]
  
  robot:
    build:
      context: .
      dockerfile: resources/docker/robot/Dockerfile
    depends_on:
      - server
      - zalenium
    environment:
      - SELENIUM_URL=http://localhost:4444
      - ROBOT_ARGS
    volumes:
      - ./test/robot:/home/robot/test/robot
      - ./test/logs:/home/robot/test/logs
      - ./test/variables.py:/home/robot/test/variables.py
    network_mode: host

